name = "LyceumCore"
uuid = "e5bd5517-2193-49f0-ba9c-d5a8508cb639"
authors = ["Colin Summers", "The Contributors of LyceumCore"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
